name: MultiSigWallet CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js 16.14.0
      uses: actions/setup-node@v2
      with:
        node-version: '16.14.0'
        cache: 'npm'
        
    - name: Show Node.js version    
      run: npm --version
    
    - name: Install Truffle (globaly)
      #run: npm install truffle@5.4.24 -g
      run: npm install -g truffle

    - name: Install Solhint (globaly)
      run: npm install -g solhint

    - name: Install dependencies
      run: npm install
    
    - name: Show versions (truffle)
      run: truffle version
      
    - name: Show versions (solhint)
      run: npx solhint --version

    - name: Run and Check Solhint
      run: npx solhint 'contracts/**/*.sol' -f stylish

  analyze:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - uses: crytic/slither-action@v0.1.1
          with:
            target: 'contracts/'